services:
  postgres:
    image: postgres:16.2-alpine
    networks:
      - bank-network
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=meta-bank
    ports:
      - "5432:5432"
    volumes:
      - ./db-data/postgres:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - app.env
    environment:
      - DB_SOURCE
      - REGISTRY_HTTP_RELATIVEURLS=true
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]

  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./db-data/redis:/data

  mailhog:
    image: mailhog/mailhog:latest
    platform: linux/amd64
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always

networks:
  bank-network:
    name: bank-network

volumes:
  data-volume:
