apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - rolearn: "arn:aws:iam::569776826105:user/github-ci"
      username: github-ci
      groups:
        - system:masters
